[build]
builder = "nixpacks"
buildCommand = "./mvnw clean package"
root = "backend"
watchPaths = ["backend/**"]

[deploy]
startCommand = "java -jar target/backend-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
