export const iconMap: { [key: string]: string } = {
  Java: '/icons/java-original.png',
  JavaScript: '/icons/javascript-original.png',
  TypeScript: '/icons/typescript-original.png',
  'HTML/CSS': '/icons/html5-original.png',
  'Spring Boot': '/icons/spring-original.png',
  IntelliJ: '/icons/intellij-original.png',
  Docker: '/icons/docker-original.png',
  Jenkins: '/icons/jenkins-original.png',
  Bash: '/icons/bash-original.png',
  Git: '/icons/git-original.png',
  Gradle: '/icons/gradle-original.png',
  Vite: '/icons/vite-original.png',
  React: '/icons/react-original.png',
  MySQL: '/icons/mysql-original.png',
  SQLite: '/icons/sqlite-original.png',
}
