import { StyleSheet } from '@react-pdf/renderer'
import { pdfThemeColors } from '@/work/pdf/pdfThemecolors'

export const styles = StyleSheet.create({
  page: {
    paddingTop: 22,
    paddingBottom: 22,
    paddingHorizontal: 0,
    fontFamily: 'Open Sans',
    backgroundColor: pdfThemeColors.pageBackground,
    fontSize: 8.5,
    color: pdfThemeColors.pageText,
    lineHeight: 1.3,
  },
  bodyPadding: {
    paddingHorizontal: 32,
  },
  headerSection: {
    backgroundColor: '#f3f4f6',
    paddingHorizontal: 32,
    paddingTop: 14,
    paddingBottom: 10,
    marginBottom: 10,
  },
  section: {
    marginBottom: 7,
    padding: 8,
    backgroundColor: '#ffffff',
    borderRadius: 5,
    borderTopWidth: 1,
    borderTopColor: '#eeeeee',
  },
  profileImage: {
    width: 54,
    height: 62,
    borderRadius: 35,
    borderWidth: 2,
    borderColor: pdfThemeColors.highlight,
    marginBottom: 8,
    alignSelf: 'center',
    objectFit: 'cover',
  },
  headerName: {
    fontSize: 16,
    fontFamily: 'Open Sans Bold',
    textAlign: 'center',
    color: pdfThemeColors.primaryText,
    marginBottom: 4,
  },
  headerTitle: {
    fontSize: 9,
    textAlign: 'center',
    color: pdfThemeColors.primaryText,
    marginBottom: 3,
    maxWidth: 390,
    alignSelf: 'center',
  },
  headerLink: {
    fontSize: 9,
    textAlign: 'center',
    color: pdfThemeColors.primaryText,
    textDecoration: 'none',
    marginTop: 4,
  },
  sectionTitle: {
    fontSize: 12,
    fontFamily: 'Open Sans Bold',
    marginBottom: 5,
    color: pdfThemeColors.primaryText,
    borderBottomWidth: 2,
    borderBottomColor: pdfThemeColors.highlight,
    paddingBottom: 2,
  },
  subHeading: {
    fontSize: 11,
    fontFamily: 'Open Sans Bold',
    color: pdfThemeColors.primaryText,
    marginTop: 6,
    marginBottom: 3,
  },
  text: {
    fontSize: 8.5,
    marginBottom: 2,
  },
  boldPrimaryText: {
    fontSize: 10,
    fontFamily: 'Open Sans Bold',
    color: pdfThemeColors.primaryText,
    marginBottom: 1,
  },
  listItemContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 3,
    marginBottom: 2,
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 10,
    marginBottom: 3,
    maxWidth: '45%',
  },
  projectLink: {
    fontSize: 8,
    color: pdfThemeColors.primaryText,
    textDecoration: 'none',
    marginTop: 1,
    wordBreak: 'break-all',
  },
  contactText: {
    fontSize: 8.5,
    marginBottom: 2,
  },
  contactLabel: {
    fontFamily: 'Open Sans Bold',
    color: pdfThemeColors.primaryText,
  },
  detailList: {
    marginLeft: 10,
    marginTop: 1,
  },
  detailItem: {
    fontSize: 8.5,
    marginBottom: 1,
  },
})
