export const PRICING = {
  portrait: {
    basePrice: '2 290 kr',
    baseFrom: 'Från 2 290 kr',
    baseDuration: '30 minuter',
    baseImages: '5 redigerade bilder',
    familyPrice: '3 290 kr',
    familyFrom: 'Från 3 290 kr',
    familyDuration: '45 till 60 minuter',
    familyImages: '10 redigerade bilder',
    extraImage: '250 kr/st',
  },
  wedding: {
    shortPrice: '9 500 kr',
    shortFrom: 'Från 9 500 kr',
    shortDuration: '2 timmar',
    shortImages: 'ca 75 redigerade bilder',
    halfDayPrice: '17 900 kr',
    halfDayDuration: '5 timmar',
    halfDayImages: 'ca 250 redigerade bilder',
    fullDayPrice: '28 900 kr',
    fullDayDuration: '10 timmar',
    fullDayImages: 'ca 500 redigerade bilder',
    extraHour: '2 500 kr/timme',
    highlightFilmWithPhoto: '5 000 kr',
    highlightFilmStandalone: '8 000 kr',
  },
  business: {
    portraitFrom: '2 500 kr',
    eventFrom: '5 500 kr',
    eventFullDayFrom: '14 900 kr',
    activityHourlyFrom: '2 200 kr/h',
    productStartFrom: '3 500 kr',
    productIncludedImages: 10,
    productExtraImageFrom: '250 kr/st',
    taxNote: 'Moms tillkommer inte.',
  },
  web: {
    landingPageFrom: '4 500 kr',
    websiteFrom: '8 500 kr',
    seoSupportFrom: '2 000 kr/månad',
  },
  campaigns: {
    portraitIntro: {
      enabled: false,
      label: 'Introduktionserbjudande',
      originalPrice: '2 290 kr',
      campaignPrice: '1 990 kr',
      validUntil: '',
    },
    weddingSeason: {
      enabled: false,
      label: 'Säsongserbjudande',
      originalPrice: '9 500 kr',
      campaignPrice: '8 900 kr',
      validUntil: '',
    },
  },
} as const

export const PRICE_ESTIMATOR = {
  portrait: {
    base: 2290,
    extraImage: 250,
    extraThirtyMinutes: 1000,
  },
  family: {
    base: 3290,
    extraImage: 250,
    extraThirtyMinutes: 1000,
    largeGroupSupplement: 750,
  },
  wedding: {
    short: 9500,
    halfDay: 17900,
    fullDay: 28900,
    extraHour: 2500,
    highlightFilm: 5000,
  },
  businessPortraits: {
    firstPerson: 2500,
    personTwoToFive: 1250,
    personSixToTen: 900,
    groupImage: 1000,
    quoteAbovePeople: 10,
  },
  businessActivity: {
    hourly: 2200,
    minimumHours: 2,
  },
  product: {
    base: 3500,
    includedImages: 10,
    extraImage: 250,
    extraSetup: 750,
  },
  vehicle: {
    base: 2990,
    includedImages: 10,
    extraImage: 250,
  },
  travel: {
    perRoundTripMil: 20,
    roundTo: 10,
  },
  priorityDelivery: {
    rate: 0.25,
    minimum: 750,
  },
} as const
