name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      # Steg 1: Check out repository med full historik
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # För att säkerställa att hela historiken hämtas

      # Steg 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Steg 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Steg 4: Build project with Vite
      - name: Build project
        run: npm run build

      # Steg 5: Add CNAME file for custom domain
      - name: Add CNAME file
        run: echo "www.svendsenphotography.com" > docs/CNAME

      # Steg 6: Commit and push changes to main branch
      - name: Commit and push changes
        env:
          GIT_AUTHOR_NAME: "daniel-svendsen"
          GIT_AUTHOR_EMAIL: "daniel-svendsen@hotmail.se"
          GIT_COMMITTER_NAME: "daniel-svendsen"
          GIT_COMMITTER_EMAIL: "daniel-svendsen@hotmail.se"
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"
          git add docs
          git commit -m "Deploy to GitHub Pages [skip ci]"
          git push https://x-access-token:${PAT_TOKEN}@github.com/daniel-svendsen/daniel-svendsen.github.io.git HEAD:main

