name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Kör varje gång kod pushas till main
  workflow_dispatch:  # Manuell trigger om du vill köra det själv

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Add custom domain
        run: echo "www.svendsenphotography.com" > dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          branch: gh-pages
